name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: '0.11.0'

    - name: Build Zig Project
      run: |
        zig build

    - name: Prepare the artifacts
      run: |
        mkdir ../artifacts
        cp -r web/* ../artifacts/

    - name: Checkout release branch
      uses: actions/checkout@v2
      with:
        ref: release
        fetch-depth: 0

    - name: Copy build artifacts to root of release branch
      run: |
        git rm -r *
        cp -r ../artifacts/* .
        git add .
        git status

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Deploy build artifacts to release branch" -a || echo "No changes to commit"
        git push origin release
